services:
    -   type: web
        name: backend-flask-qcm
        env: python
        plan: free
        buildCommand: "pip install -r requirements.txt"
        startCommand: "python app.py"
        runtime: python
